### PR TITLE
Add support for other program types

### PR DESCRIPTION
**Pull request by bkg**
I am hoping to add support for other supervisor program types like [eventlistener](http://supervisord.org/configuration.html#eventlistener-x-section-settings) and [fcgi-program](http://supervisord.org/configuration.html#fcgi-program-x-section-settings). 

I have implemented this in a generic manner to allow for the eventlistener and fastcgi specific params to be appended to the .ini file as arbitrary key/value pairs. This provides flexibility without cluttering the `supervisor::service` attributes with program specific settings. 

Here is a basic example that uses the memmon command from the [superlance](http://superlance.readthedocs.org/en/latest/memmon.html) plugins:

```puppet
supervisor::service { 'memmon':
  command => 'memmon -a 200MB -m someone@somewhere.com'
  type => 'eventlistener',
  ini_append => {
    events => 'TICK_60',
  },
}
```

### CODE REVIEW

**Comment by plathrop** [comment]
Closing due to lack of response, feel free to reopen.

**Comment by bkg** [comment]
Hi, I'm definitely still interested in getting this merged. I have been running it in production awhile without any problems.

**Comment by plathrop** [comment]
I'll merge it then, for lack of objection - and if someone gets annoyed they can PR a revert :-)

**Comment by bkg** [comment]
Nice, much appreciated!

**Pull request merged**
